# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 670)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background:qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.title_edit.setGeometry(QtCore.QRect(0, 20, 721, 51))
        self.title_edit.setObjectName("title_edit")
        self.text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.text_edit.setGeometry(QtCore.QRect(0, 80, 721, 741))
        self.text_edit.setStyleSheet("backround:qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))")
        self.text_edit.setObjectName("text_edit")
        self.list_btn = QtWidgets.QListWidget(self.centralwidget)
        self.list_btn.setGeometry(QtCore.QRect(750, 40, 381, 231))
        self.list_btn.setObjectName("list_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(750, 20, 108, 19))
        self.label.setObjectName("label")
        self.delete_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn_2.setGeometry(QtCore.QRect(950, 280, 181, 31))
        self.delete_btn_2.setObjectName("delete_btn_2")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(750, 280, 191, 31))
        self.create_btn.setObjectName("create_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(750, 320, 381, 31))
        self.save_btn.setObjectName("save_btn")
        self.list_btn_2 = QtWidgets.QListWidget(self.centralwidget)
        self.list_btn_2.setGeometry(QtCore.QRect(750, 390, 381, 231))
        self.list_btn_2.setObjectName("list_btn_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(750, 370, 89, 19))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(750, 630, 381, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(750, 660, 181, 31))
        self.add_btn.setObjectName("add_btn")
        self.unpin_btn = QtWidgets.QPushButton(self.centralwidget)
        self.unpin_btn.setGeometry(QtCore.QRect(950, 660, 181, 31))
        self.unpin_btn.setObjectName("unpin_btn")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(750, 700, 381, 31))
        self.search_btn.setObjectName("search_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1149, 26))
        self.menubar.setObjectName("menubar")
        self.menueasy_ez_ez = QtWidgets.QMenu(self.menubar)
        self.menueasy_ez_ez.setObjectName("menueasy_ez_ez")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menueasy_ez_ez.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.6pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "список заміток"))
        self.delete_btn_2.setText(_translate("MainWindow", "видалити замітку"))
        self.create_btn.setText(_translate("MainWindow", "створити замітку"))
        self.save_btn.setText(_translate("MainWindow", "зберегти замітку"))
        self.label_2.setText(_translate("MainWindow", "список тегів"))
        self.lineEdit_2.setText(_translate("MainWindow", "пиши щось тут"))
        self.add_btn.setText(_translate("MainWindow", "додати до замітки"))
        self.unpin_btn.setText(_translate("MainWindow", "відкріпити від замітки"))
        self.search_btn.setText(_translate("MainWindow", "Шукати замітки по тегу"))
        self.menueasy_ez_ez.setTitle(_translate("MainWindow", "easy ez ez"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
